service: crazy-slot

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  
functions:
  main:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: any
    environment:
      # 環境変数をここに追加
      NODE_ENV: production

plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.gitignore'
    - '!.env'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json' 